apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  AUTH: "mongodb+srv://sujalpanchal249_db_user:88vtnWhoVYl6i5dT@cluster0.lpqrt00.mongodb.net/auth"
  SANDBOX: "mongodb+srv://sujalpanchal249_db_user:88vtnWhoVYl6i5dT@cluster0.lpqrt00.mongodb.net/sandbox"
  AI: "mongodb+srv://sujalpanchal249_db_user:88vtnWhoVYl6i5dT@cluster0.lpqrt00.mongodb.net/ai"
  REDIS_URL: "redis://default:A9BZK2WTSrANjoMuFMz02ES4KnXQDsg0@letters-hook-jadeish-88721.db.redis.io:13032"

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_SECRET: 1d739bcd323741c72f52398f1fc66146200737a540d511b19f868242c198d88d58c48e8c737bd775e50d958c

---
apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: 437241590710-ce84o2fcqnbg1esivhsbgcdr8cpfs0m3.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secret
type: Opaque
stringData:
  MISTRALAI_API_KEY: SJTJjnlIVhkYTlCiWz5cNEaKgX2DD6p1
