FROM node:20-alpine

WORKDIR /workspace

# dependencies first (better caching)
COPY package*.json ./

RUN npm install

# copy source
COPY . .

EXPOSE 5173

# IMPORTANT: force host binding
CMD ["npm", "run", "dev"]